/* Maison Rouge — page Résultats : preuves Avant/Après authentiques organisées comme une galerie éditoriale, sans faux témoignages. */
import { ArrowUpRight, Play } from "lucide-react";
import { SiteNav } from "@/components/SiteNav";

const cases = [
  { handle: "@laulaupoussedelafonte", field: "Sport & perte de gras", multiplier: "×21", before: "2 982", after: "62,4k", beforeImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-laulau-avant_5baf79db.png", afterImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-laulau-apres_4e151c07.png" },
  { handle: "@laurianne_hrl", field: "Voyage & lifestyle", multiplier: "×79", before: "1 514", after: "119k", beforeImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-laurianne-avant_4ddeb513.png", afterImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-laurianne-apres_dc36ee0a.png" },
  { handle: "@emmeline", field: "Création de contenu", multiplier: "Avant / Après", before: "Avant", after: "Après", beforeImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-emmeline-avant_774e031f.png", afterImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-emmeline-apres_29f7d06a.png" },
  { handle: "@lisa", field: "Lifestyle & communauté", multiplier: "Avant / Après", before: "Avant", after: "Après", beforeImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-lisa-avant_1f24e666.png", afterImg: "https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/ba-lisa-apres_9e5b8c58.png" },
];

export default function ResultsPage() {
  return (
    <div className="editorial-page results-page"><SiteNav /><main>
      <section className="results-hero"><div className="editorial-shell"><p className="page-kicker">Avant / Après</p><h1>Des comptes qui ont <em>décollé.</em></h1><p>Des captures et des résultats partagés par les personnes accompagnées. Des preuves visibles, sans promesses retouchées.</p></div></section>
      <section className="results-gallery"><div className="editorial-shell"><div className="results-gallery-head"><p>Résultats de la communauté</p><a href="https://www.instagram.com/mathildewod/" target="_blank" rel="noreferrer">Voir plus sur Instagram <ArrowUpRight size={15} /></a></div><div className="case-grid">{cases.map((item) => <article className="case-card" key={item.handle}><div className="case-head"><div><strong>{item.handle}</strong><span>{item.field}</span></div><b>{item.multiplier}</b></div><div className="case-shots"><div className="case-shot"><small>Avant</small><figure><img src={item.beforeImg} alt={`Capture avant ${item.handle}`} /></figure><em>{item.before}</em></div><div className="case-shot after"><small>Après</small><figure><img src={item.afterImg} alt={`Capture après ${item.handle}`} /></figure><em>{item.after}</em></div></div></article>)}</div></div></section>
      <section className="results-video-section"><div className="editorial-shell video-page-grid"><div><p className="page-kicker">Elles racontent leur déclic</p><h2>Les récits derrière les <em>chiffres.</em></h2><p>Deux retours vidéo de membres de la communauté, partagés depuis les contenus fournis.</p></div><div className="results-videos"><article><video controls preload="metadata" src="https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/temoignage-elsacoachyoga_aa545ae7.mp4" /><span><Play size={12} fill="currentColor" /> Elsa Coach Yoga</span></article><article><video controls preload="metadata" src="https://raw.githubusercontent.com/essidyoussef-source/mathildewod/main/client/public/manus-storage/temoignage-ninadiet_ab6b6f90.mp4" /><span><Play size={12} fill="currentColor" /> Nina Diet</span></article></div></div></section>
    </main></div>
  );
}
